.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH masumi 1 "February  15, 2011"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
Masumi \- A Multi-platform Japanese Language Learning Tool
.SH SYNOPSIS
.B jldrill
Right now Masumi does precisely nothing.  It opens up a window
with an icon.  You can close it if you want.
.PP
This man page is only a stub.  
.SH OPTIONS
There are no options for Masumi.
.SH AUTHOR
Masumi was written by Mike Charlton <mikekchar@gmail.com>.
